### ISSUE TITLE
How to reproduce the result?

### ISSUE THREAD

**Issue by Sharpiless** [raspberryice/ala-gcn#1]
Thank you very much for your open source contribution. But I found some problems with the train.py code, such as a lack of definition for dataloader. Could you please release the code of paper reproduction?

**Comment by raspberryice** [comment]
`DataLoader` is a class defined in `pytorch.utils.data`.

**Comment by raspberryice** [comment]
Hi Sharpiless, 
Apologies for misunderstanding your question. The issue is related to the version of `pytorch-lightning` you are using.
