### ISSUE TITLE
Could you let me know which version of pytorch-lightning did you use?

### ISSUE THREAD

**Issue by Wallace-222** [raspberryice/ala-gcn#2]
It seems that the current code does not align to the latest version of pytorch-lighting. Can you verify whether the current code with the latest pytorch-lighting?

**Comment by Twsschx** [comment]
come up with the same problem.

AttributeError: module 'pytorch_lightning' has no attribute 'data_loader'

**Comment by raspberryice** [comment]
Hi guys, 
The version that was used for developing is `0.5.3.2`. `pytorch_lightning` APIs change pretty fast. Sorry for the confusion.

**Comment by Ruijia-Xu** [comment]
hello @raspberryice 
I simply run "python train.py --percentage=0.01" for adagat，but the result is 5 points smaller than the result in table 3 (1% cora ALaGAT). Could you give some insights how to debug?
